[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "keep_walking.settings"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning"
]

[project]
name = "keep-walking"
version = "0.0.1"