# Generated by Django 3.2.20 on 2023-08-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmindata',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
