# Generated by Django 3.2.20 on 2023-09-02 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0003_remove_garmindata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmindata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garmin_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
