# Generated by Django 3.2.20 on 2023-09-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmindata',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Bad'), (1, 'Neutral'), (2, 'Good'), (3, 'Undefined')], default=3),
        ),
        migrations.DeleteModel(
            name='Emotion',
        ),
    ]
