# Generated by Django 3.2.20 on 2023-09-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
