# Generated by Django 3.2.20 on 2023-09-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_userprofile_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height_cm',
            field=models.IntegerField(default=170),
        ),
    ]
