# Generated by Django 3.2.20 on 2023-10-03 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0009_alter_userprofile_height_cm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_weight', models.FloatField()),
                ('avg_bmi', models.FloatField()),
                ('avg_bmi_change', models.FloatField()),
                ('bmi_in_healthy_range', models.BooleanField()),
                ('bmi_improving_or_maintaining', models.BooleanField()),
                ('date', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_average', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
